name: burrito_prod

services:
  burrito_server:
    build:
      context: .
      dockerfile: ./docker/prod/Dockerfile
    expose:
      - 6969
    environment:
      - ROCKET_PORT=6969
      - ROCKET_ADDRESS=0.0.0.0
      - ROCKET_LOG_LEVEL=debug
    depends_on:
      - burrito_db
      - burrito_nginx
    restart: always

  burrito_db:
    image: postgres:16.4-bullseye
    env_file:
      - .env
    environment:
      - POSTGRES_DB=burrito_app
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: always
    volumes:
      - burrito_db_data:/var/lib/postgresql/data

  burrito_nginx:
    build:
      context: .
      dockerfile: ./docker/prod/nginx/Dockerfile
      args:
        - DOMAIN_NAME=api.burritosanmarcos.com
        - WEB_DOMAIN_NAME=burritosanmarcos.com
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /home/paoloose/www/burrito:/var/www/burrito:rw
    restart: always

volumes:
  burrito_db_data:
